### ISSUE TITLE
`Show` instance of `SNat` uses `dN` for large values of `N`

### ISSUE THREAD

**Issue by gergoerdi** [clash-lang/clash-compiler#1038]
(Clash 1.0.1)

The `Show` instance of `SNat` outputs the `d`*n* helper functions, e.g.:

```
Clash.Prelude> show (SNat @1024)
"d1024"
```

This roundtrips for small values of *n*:

```
Clash.Prelude> :t d1024
d1024 :: SNat 1024
```

However, for larger *n*, there are no `d`*n* helpers defined in the standard library:

```
Clash.Prelude> show (SNat @1025)
"d1025"
Clash.Prelude> :t d1025

<interactive>:1:1: error:
    • Variable not in scope: d1025
```

Wouldn't it make sense to either always show it as `SNat @n`, or to fall back to that for *n* > 1024?

**Comment by martijnbastiaan** [comment]
> Wouldn't it make sense to either always show it as SNat @n, or to fall back to that for n > 1024?

Makes sense to me! I'd prefer the latter, as the `dN` notation is slightly more compact than `SNat @N`.
