### ISSUE TITLE
When ghc is not in path, clash won't run (with horrible error message)

### ISSUE THREAD

**Issue by ggreif** [clash-lang/clash-compiler#104]
Issue #82 describes a problem where clash queried the "wrong" GHC. This time it would query the right one, but (if) it is not in path, so it fails with
```
fd:5: hGetLine: end of file
```

This is a rather low-prio bug, I just handed over a full pathname to clash to another colleague and he could not start it. Turned out that he had to add my `~/bin` to his path.

Catching this error and issuing a nice error message along the lines of `Could not invoke the GHC compiler that CLaSH was built with. Make sure it is in your $PATH` would be a big plus.

**Comment by christiaanb** [comment]
You should now get:

```
~/devel/clash-compiler(master *) $ ./clash-ghc/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/clash/clash --interactive
CLaSH needs the GHC compiler it was build with, ghc-7.10.2, but it was not found. Make sure its location is in your PATH variable.
```
