### ISSUE TITLE
Port naming error detection logic not always working

### ISSUE THREAD

**Issue by leonschoorl** [clash-lang/clash-compiler#1063]
```haskell
module TestNaming where
import Clash.Prelude

type T = Bool -- error as expected
-- type T = Int  -- no error :(

{-# ANN topEntity (defSyn "top")
  {t_inputs = [PortProduct "wrong" [PortName "one", PortName "two"]]}
  #-}
topEntity :: T -> T
topEntity = id
```
Returns an error as expected:
```
*** Exception: Clash.Netlist.Util(635): Ports were annotated as product, but type wasn't one: 

   Filtered was: FilteredHWType Bool []

   Ports was: PortProduct "wrong" [PortName "one",PortName "two"]
```

But if I change `T` to be `Int` clash will happily name the resulting in port `wrong`.

**Comment by leonschoorl** [comment]
I guess it's technically true that in haskell Int is a one element product type: 
```haskell
data Int = GHC.Types.I# GHC.Prim.Int#
```
But that's not how clash handles it.
It names the port just `wrong`, not `wrong_one`.

**Comment by christiaanb** [comment]
@leonschoorl Clash should not recognize `Int` as a one-product. https://github.com/clash-lang/clash-compiler/blob/ee45c470acafa522db754c7327ca1ea58b71cdc1/clash-lib/src/Clash/Netlist/Util.hs#L430 should prevent that. If it's not, then something is wrong with https://github.com/clash-lang/clash-compiler/blob/ee45c470acafa522db754c7327ca1ea58b71cdc1/clash-lib/src/Clash/Netlist/Util.hs#L406
