### ISSUE TITLE
'splitTopAnn' fails for certain top entities

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#1074]
Example:

```haskell
{-# ANN topEntity
  (Synthesize
    { t_name   = "top"
    , t_inputs =
        [ PortProduct "" [PortName "theClock", PortName "theReset"]
        , PortName "theInput"
        ]
    , t_output = PortName "theResult"
    }
  )#-}
topEntity
  :: forall dom1
   . dom1 ~ System
  => forall dom2
   . dom2 ~ System
  => (Clock dom1, Reset dom2)
  -> Signal dom1 Int
  -> Signal dom2 Int
topEntity (clk, rst) = id
```

**Comment by leonschoorl** [comment]
Is it because of the two foralls?

**Comment by martijnbastiaan** [comment]
Exactly. It goes into an "eq removal" loop followed by the actual logic after seeing a number of foralls. But it should keep removing foralls/eqs until it sees something that's neither a forall nor an eq.

**Comment by leonschoorl** [comment]
@martijnbastiaan Did you maybe test before you merged https://github.com/clash-lang/clash-compiler/pull/1072?
Because this seems to just work now.

**Comment by leonschoorl** [comment]
If I add an extra (non-equality) constraint in between the first and second forall then it does break:
```haskell
topEntity
  :: forall dom1
   . dom1 ~ System
  => HasCallStack
  => forall dom2
   . dom2 ~ System
  => (Clock dom1, Reset dom2)
  -> Signal dom1 Int
  -> Signal dom2 Int
```

**Comment by martijnbastiaan** [comment]
It also breaks for things on `Vec`.
