### ISSUE TITLE
The NFData constraint on maybeX and maybeIsX is unnecessary

### ISSUE THREAD

**Issue by expipiplus1** [clash-lang/clash-compiler#1075]

**Comment by martijnbastiaan** [comment]
You're right, thanks!

https://github.com/clash-lang/clash-compiler/pull/1076

**Comment by expipiplus1** [comment]
Thanks for the quick fix

**Comment by basile-henry** [comment]
@expipiplus1 Still using Clash? :smile:

**Comment by expipiplus1** [comment]
@basile-henry Not too much at the moment sadly, but it's a frequent topic of conversation over here.
