### ISSUE TITLE
Is `enumFrom` supposed to give infinite list for `Unsigned n` and `Signed n`?

### ISSUE THREAD

**Issue by gergoerdi** [clash-lang/clash-compiler#1089]
Is the following really the intended behaviour of `enumFrom` for `Unsigned n` and `Signed n`?

```
Clash.Prelude Data.Word> [(250 :: Word8)..] 
[250,251,252,253,254,255]

Clash.Prelude Data.Word> [(250 :: Unsigned 8)..] 
[250,251,252,253,254,255,0,1,2,3,4,5,6,7,8,9,10,11,12,13...
```

**Comment by leonschoorl** [comment]
No, I think we should respect the `maxBound` just like `Word8` does.
And this is also what the documentation for Enum states (https://hackage.haskell.org/package/base-4.12.0.0/docs/Prelude.html#t:Enum)
> enumFrom and enumFromThen should be defined with an implicit bound
