### ISSUE TITLE
Prelude configuration

### ISSUE THREAD

**Issue by flip111** [clash-lang/clash-compiler#115]
Is there any way to configure the prelude as with ghci? For example i have this as ghci config

```
:set prompt "\ESC[34mλ> \ESC[m"
:set prompt2 "\ESC[34m_> \ESC[m"
:set +m
# :set -Wall
```

especially the multiline is very useful

**Comment by christiaanb** [comment]
Instead of a `.ghci` file, you need a `.clashi` file.

**Comment by flip111** [comment]
works :+1:
