### ISSUE TITLE
Type checking never finishes

### ISSUE THREAD

**Issue by rowanG077** [clash-lang/clash-compiler#1173]
The following function will never finish compiling (as in normal compilation not synthesis):

```
f :: (KnownNat l, (l * 2) ~ Max (l + l) 1) => SNat l -> SNat l
f = id
```

I believe this is due to interaction between the various solvers since the following functions work perfectly fine:

```
g :: (KnownNat l, (l + l) ~ Max (l + l) 1) => SNat l -> SNat l
g = id

h :: (KnownNat l, (l * 2) ~ (l + l)) => SNat l -> SNat l
h = id
```

**Comment by christiaanb** [comment]
GHC is violating one of the assumptions the plugins made. It's seeing:

```
[G] $d~_a1ux {0}:: fsk_a1uu[fsk:1] ~ fsk_a1uu[fsk:1] (CDictCan)
```

Now, usually, all constraints with `~` are usually as `CFunEqCan` or `CTyEqCan`; and the plugins don't try to normalize inside those given constraints. However, this time it's tagged as a `CDictCan`, normally used for things like `Num a`; and the plugins do normalize inside those.

This might be related to boxed `~` used for deferred type errors and unboxed `~` to represent actual equality.
