### ISSUE TITLE
`unfoldr` for Vec

### ISSUE THREAD

**Issue by gergoerdi** [clash-lang/clash-compiler#1220]
I'd like to propose the following addition to Clash.Sized.Vector:

```
unfoldr :: SNat n -> (s -> (a, s)) -> s -> Vec n a
```

I have an implementation in terms of `generate`, but it (safely) uses a partial function internally. A recursive, direct implementation of course wouldn't have this shortfall; which is why I think this functionality should be exposed by `Clash.Sized.Vector`.

```
unfoldr :: SNat n -> (s -> (a, s)) -> s -> Vec n a
unfoldr n f s0 = map unpack $ generate n f' (Nothing, s0)
  where
    f' (_, s) = let (x, s') = f s in (Just x, s')
    unpack (Just x, _) = x

unfoldrI :: (KnownNat n) => (s -> (a, s)) -> s -> Vec n a
unfoldrI = unfoldr SNat
```

If anyone's curious, I needed it to write the following function:

```
loadVec :: (KnownNat n) => [a] -> a -> Vec n a
loadVec xs x0 = unfoldrI uncons xs
  where
    uncons (x:xs) = (x, xs)
    uncons [] = (x0, [])
```

What do you think?

**Comment by christiaanb** [comment]
you can use a total function using some tying-the-knot shenanigans:

```haskell
unfoldrI :: KnownNat n => (s -> (a,s)) -> s -> Vec n a
unfoldrI f s0 = map fst xs
 where
  xs = init (f s0 `Cons` ws)
  ws = map (f . snd) (lazyV xs)
```

I agree we should add it though.
