### ISSUE TITLE
SaturatingMode::SatWrap can not be synthesized for Fixed

### ISSUE THREAD

**Issue by ra1u** [clash-lang/clash-compiler#123]
for example

     topEntity:: (SFixed 2 6) -> (SFixed 2 6) -> (SFixed 2 6)
     topEntity = satPlus SatWrap 

Works emulated in interpreter, but yields error when synthesised

    <no location info>:
        CLaSH Error:
    CLaSH.Normalize.Transformations(220): Report as bug: caseCon error: case CLaSH.Class.Num.SatWrap of
      CLaSH.Class.Num.SatBound ->
        CLaSH.Sized.Internal.Signed.minBound#
        @8
          8
      CLaSH.Class.Num.SatZero -> lvl5303
      CLaSH.Class.Num.SatSymmetric -> lvl8319

This code get synthesised with other `SaturatingMode`
that is  `SatBound` , `SatZero` and  `SatSymmetric`

Workaround for me was

    plusWraped:: NumSFixedC n1 n2 => SFixed n1 n2 -> SFixed n1 n2 -> SFixed n1 n2
    plusWraped a b = Fixed ((unSF a) + (unSF b))

**Comment by christiaanb** [comment]
Glad you found a work-around. I will fix this when I get back in the office on monday.

**Comment by ra1u** [comment]
Thank you for your fast and promptly support.
