### ISSUE TITLE
Support GHC 8.10

### ISSUE THREAD

**Issue by alex-mckenna** [clash-lang/clash-compiler#1245]
As GHC 8.10 is now released, we should add support to Clash. This should just be a straightforward case of adding a new `UI` Module, although the changes to module hierarchy in the 8.10 API may make this more challenging.

TODO

  - [x] Support compiling clash with GHC 8.10
  - [x] Add GHC 8.10 to the CI image and use for testing
  - [ ] Backport to 1.2 branch (?)
  - [ ] Add steps for supporting new GHC to "hacking on clash" documentation

**Comment by martijnbastiaan** [comment]
> although the changes to module hierarchy in the 8.10 API may make this more challenging.

We should use [ghc-api-compat](https://hackage.haskell.org/package/ghc-api-compat) until the hierarchy is stable and we've dropped all GHCs without the stable hierarchy IMO.

Should we drop GHC 8.4 after doing this?

**Comment by alex-mckenna** [comment]
Will dropping support for 8.4 affect users? To be safe, I think it might be better to announce end of life for GHC 8.4 support (and then drop it in say, Clash 1.4.)

**Comment by martijnbastiaan** [comment]
Oh yeah, we definitely wouldn't drop it for 1.2. Just master / Clash 1.4.

**Comment by alex-mckenna** [comment]
Assigning @leonschoorl, as he's been working on this issue the past few days.
