### ISSUE TITLE
Term-level `hzToPeriod` has different behaviour than type-level `Div`

### ISSUE THREAD

**Issue by gergoerdi** [clash-lang/clash-compiler#1253]
One would hope that the following would be a matching type-level version of `hzToPeriod`:

```
type HzToPeriod (freq :: Nat) = 1_000_000_000_000 `Div` freq
```

However, because `hzToPeriod` rounds up, and `Div` rounds down, instead we have to write

```
type HzToPeriod (freq :: Nat) = (1_000_000_000_000 + freq - 1) `Div` freq
```

Unless there is a good reason to round up, I think it would be worth changing the implementation of `hzToPeriod` (it would only change the result by 1 picosecond at most!) to be more amenable to a type-level implementation.

**Comment by DigitalBrains1** [comment]
The new `hzToPeriod` should always give the same result as the simple

```
type HzToPeriod (freq :: Nat) = 1_000_000_000_000 `Div` freq
```

(the difference being that `hzToPeriod` also supports fractional frequencies)
