### ISSUE TITLE
Irrefutable pattern failed error

### ISSUE THREAD

**Issue by ra1u** [clash-lang/clash-compiler#126]
module MovingAvg where
    import CLaSH.Prelude

    windowN :: (Default a,KnownNat n) => SNat (n+1) -> Signal a -> Vec (n + 1) (Signal a)
    windowN size = window
    movingAvarageNaive size signal =  fold (+) <$> bundle (windowN size signal)

    topEntity :: Signal (Signed 9) -> Signal (Signed 9)
    topEntity = movingAvarageNaive d5

Fails at synthesis with

    [1 of 1] Compiling MovingAvg        ( movingAvarege.hs, movingAvarege.o )
    Loading dependencies took 0.259644s
    clash: panic! (the 'impossible' happened)
      (GHC version 7.10.3 for x86_64-unknown-linux):
        src/CLaSH/Normalize/PrimitiveReductions.hs:250:9-46: Irrefutable pattern failed for pattern [_, consCon]

    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

**Comment by christiaanb** [comment]
I think I know what's going on here, I'll fix it when I get back in the office tomorrow morning. Thanks for the bug report.

**Comment by christiaanb** [comment]
As a temporary work-around, using either `foldr1` or `fold1` would work.

**Comment by christiaanb** [comment]
I just released version 0.6.10 of CLaSH which includes this bug fix.

**Comment by ra1u** [comment]
Great, I will play around with this when I get home.
