### ISSUE TITLE
Suggestion: make clash-prelude a git submodule

### ISSUE THREAD

**Issue by ggreif** [clash-lang/clash-compiler#129]
I am just letting the idea balloon loose...

`clash-compiler` is depending on `clash-prelude` pretty heavily with respect to semantics, so why not link them in `git` also?

Would you accept a pull request?

**Comment by christiaanb** [comment]
I would, but I'm unfamiliar with the semantics of git submodules. So the pull-request should also update the `.travis.yml` and `stack.yaml` accordingly. And preferably you could see to update the [wiki page](https://github.com/clash-lang/clash-compiler/wiki/Getting-started) on how to get started on hacking on CLaSH also then?

**Comment by ggreif** [comment]
Might take some rounds, but we'll get there :-)

**Comment by ggreif** [comment]
I made a first draft in pull request #130. Let's see whether it tests.

**Comment by christiaanb** [comment]
#130 is merged

**Comment by ggreif** [comment]
Great, I have updated the wiki!
