### ISSUE TITLE
Cannot build Clash on Windows 10 insider preview natively

### ISSUE THREAD

**Issue by christiaanb** [clash-lang/clash-compiler#1290]
My system details:
```
> systeminfo /fo csv | ConvertFrom-Csv | select OS*, System*, Hotfix* | Format-List


OS Name             : Microsoft Windows 10 Home
OS Version          : 10.0.19041 N/A Build 19041
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Standalone Workstation
OS Build Type       : Multiprocessor Free
System Boot Time    : 24-4-2020, 08:20:00
System Manufacturer : HP
System Model        : HP Pavilion Gaming Laptop 17-cd0xxx
System Type         : x64-based PC
System Directory    : C:\WINDOWS\system32
System Locale       : en-us;Engels (Verenigde Staten)
Hotfix(s)           : 4 Hotfix(s) Installed.,[01]: KB4534170,[02]: KB4537759,[03]: KB4545706,[04]: KB4558244
```

The issue is that we need GHC 8.8.3 (or higher) to work around issue (or issues similar to): https://gitlab.haskell.org/ghc/ghc/issues/17599

However, GHC 8.8.3 (and GHC 8.10.1) has the following bug for the newer insider preview builds of Windows 10: https://gitlab.haskell.org/ghc/ghc/issues/17926

i.e. if you're on Windows 10 Insider Preview, your only work-around is WSL2 at this point in time.

## Work-around instructions for installing Clash on Windows 10 insider preview
1. [Install WSL2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)
3. [Install Nix](https://nathan.gs/2019/04/12/nix-on-windows/) on your WSL2 distro
5. `curl -s -L https://github.com/clash-lang/clash-compiler/archive/1.2.tar.gz | tar xz`
6. `nix-shell clash-compiler-1.2/shell.nix`

you should now have a shell where you can `clash` and `clashi`

**Comment by martijnbastiaan** [comment]
GHC 8.10.4 fixes these issues :).
