### ISSUE TITLE
0.6.11 CLaSH.Netlist(376): Not in normal form: application of a Let/Lam/Case

### ISSUE THREAD

**Issue by masterdezign** [clash-lang/clash-compiler#132]
Hello! The newest CLaSH version introduces a strange error message, which was not the case in the previous versions.

<no location info>:
    CLaSH Error:
CLaSH.Netlist(376): Not in normal form: application of a Let/Lam/Case: (λ(w3 :: CLaSH.Signal.Internal.Signal'
           (CLaSH.Signal.Internal.Clk system 72)
           (GHC.Tuple.(,,)
              (GHC.Tuple.(,)
                 (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
                 (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13))
              (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
              (CLaSH.Sized.Fixed.Fixed
                 CLaSH.Sized.Internal.Signed.Signed 3 13))) ->
 CLaSH.Prelude.Mealy.$wmealy'2075
   (GHC.Tuple.(,,,,)
    @(GHC.Tuple.(,)
        (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
        (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13))
    @(GHC.Tuple.(,)
        (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
        (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13))
    @(GHC.Tuple.(,)
        (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
        (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13))
    @(GHC.Tuple.(,)
        (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
        (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13))
    @(GHC.Tuple.(,)
        (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
        (CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13))
      (GHC.Tuple.(,)
       @(CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
       @(CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
         (CLaSH.Sized.Internal.Signed.fromInteger#
          @16
            16
            0)
         (CLaSH.Sized.Internal.Signed.fromInteger#
          @16
            16
            0))
      (GHC.Tuple.(,)
       @(CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
       @(CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
         (CLaSH.Sized.Internal.Signed.fromInteger#
          @16
            16
            0)
         (CLaSH.Sized.Internal.Signed.fromInteger#
          @16
            16
            0))
      (GHC.Tuple.(,)
       @(CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
       @(CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
         (CLaSH.Sized.Internal.Signed.fromInteger#
          @16
            16
            0)
         (CLaSH.Sized.Internal.Signed.fromInteger#
          @16
            16
            0))
      (GHC.Tuple.(,)
       @(CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
       @(CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
         (CLaSH.Sized.Internal.Signed.fromInteger#
          @16
            16
            0)
         (CLaSH.Sized.Internal.Signed.fromInteger#
          @16
            16
            0))
      (GHC.Tuple.(,)
       @(CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
       @(CLaSH.Sized.Fixed.Fixed CLaSH.Sized.Internal.Signed.Signed 3 13)
         (CLaSH.Sized.Internal.Signed.fromInteger#
          @16
            16
            0)
         (CLaSH.Sized.Internal.Signed.fromInteger#
          @16
            16
            0)))
   w3)
  result_010455

**Comment by christiaanb** [comment]
Is there any way you could provide the source? It is hard to determine what might be causing this.

**Comment by christiaanb** [comment]
I doesnt have to be a reduced test case btw. There is only one thing that I changed in version 0.6.11 that I think could be the cause of this error, but I have no idea why. My guess is, is that this change exposed another error already present for a long time.

**Comment by masterdezign** [comment]
Is private mail OK?

**Comment by christiaanb** [comment]
Yes, private email is OK, I will even sign an NDA if required.

**Comment by christiaanb** [comment]
I just released version 0.6.12, which contains the above fix.
