### ISSUE TITLE
Suggestion: Split `NFDataX` in two, allowing `deepErrorX` to be defined for `Signal`

### ISSUE THREAD

**Issue by jonfowler** [clash-lang/clash-compiler#1327]
`NFDataX` can be sensibly split into `ErrorX` and `NFDataX`. `ErrorX` contains `deepErrorX` and `ensureSpine`. `NFDataX` is a superclass which additionally contains `rnfX` and `hasUndefined`. 

This allows for `ErrorX` instances for things like `Signal` and `a -> b` (which currently has a questionable instance for `NFDataX`)

**Comment by martijnbastiaan** [comment]
I agree that they can be sensibly split up. During the introduction of `NFDataX` (and all its functions) we opted for a single class, as splitting it up would add yet another class to the list of instances you need to derive to sensibly use a type in Clash. (I.e., `ErrorX`, `NFDataX`, `Generic`, `BitVector`, `ShowX`).
