### ISSUE TITLE
Generate SDC file with clock specifications

### ISSUE THREAD

**Issue by christiaanb** [clash-lang/clash-compiler#1387]
Clash should generate an SDC file with `create_clock` commands for all `Clock` arguments of functions that are a synthesis boundary (`topEntity` or functions with a `Synthesize` annotation). For example, for https://github.com/clash-lang/clash-compiler/blob/master/examples/Blinker.hs  Clash should generate a file called `blinker.sdc` with the following content:
```tcl
create_clock -name {CLOCK_50} -period 20.000 -waveform { 0.000 10.000 } [get_ports {CLOCK_50}]
```

**Comment by alex-mckenna** [comment]
Should this change based on `hdlSyn`? Vivado uses XDC which is (from the looks of it) SDC with some Xilinx-specific extensions. A cursory search also seems to suggest SDC is largely associated with Quartus, although that may just be because Quartus is so widespread

**Comment by christiaanb** [comment]
Synopsys Design Constraint, i.e. SDC, is the industry-standard name; but I guess we could change the extension to `.xdc` if the `hdlSyn` says we're building for Vivado.

**Comment by alex-mckenna** [comment]
If it's industry standard, presumably Vivado will accept it anyway (at least, you would hope it does). I was more curious about whether this was aimed at a specific EDA tool or not
