### ISSUE TITLE
Synchronous RAM simulation is too strict in address argument

### ISSUE THREAD

**Issue by gergoerdi** [clash-lang/clash-compiler#1458]
To demonstrate this problem, I create a block RAM with 8 cells, and then try to address it with a 4-bit signal:

```
foo :: (HiddenClockResetEnable dom) => Signal dom (Unsigned 4) -> Signal dom (Unsigned 8)
foo addr = mux (register False $ addr .<. 8) ram (pure 0xff)
  where
    ram = blockRam1 NoClearOnReset (SNat @8) 0 addr (pure Nothing)
```

Since the read from RAM is guarded by a multiplexer that checks the address (from the previous cycle, since the RAM is synchronous), I would expect this to work in simulation. However, it fails seemingly because `blockRam1`'s simulation tries to interpret the out-of-bounds read address:

```
sim = L.tail $ sampleN 15 $
      let addr = fromList [0..15] in
      bundle (addr, foo addr) :: Signal System (Unsigned 4, Unsigned 8)
```

```
> mapM_ print sim
(1,255)
(2,0)
(3,0)
(4,0)
(5,0)
(6,0)
(7,0)
(8,0)
(9,255)
*** Exception: index out of bounds in call to: Data.Sequence.index 8
CallStack (from HasCallStack):
  error, called at libraries/containers/containers/src/Data/Sequence/Internal.hs:2056:7 in containers-0.6.2.1:Data.Sequence.Internal
```

Of course, one can work around this by using a dummy address when it doesn't matter:

```
foo' :: (HiddenClockResetEnable dom) => Signal dom (Unsigned 4) -> Signal dom (Unsigned 8)
foo' addr = mux (register False sel) ram (pure 0xff)
  where
    sel = addr .<. 8
    addr' = mux sel addr (pure 0)

    ram = blockRam1 NoClearOnReset (SNat @8) 0 addr' (pure Nothing)
```

**Comment by christiaanb** [comment]
Ah, so the actual issue is that we force the output elements of the Signal/Stream to WHNF using `seqX`, which only catches and (and the subsequently boxes) `XException`. But `Data.Sequence.index` throws `ErrorCall` exceptions on out-of-bounds indexing. Perhaps for the blockRam we want to use a version of `seqX` that also catches `ErrorCall` exceptions.
