### ISSUE TITLE
replicate unfolded incorrectly

### ISSUE THREAD

**Issue by tomjaguarpaw** [clash-lang/clash-compiler#150]
The code below takes a long time to compile because it unfolds `replicate`.  I know a few ways of speeding it up:

* `NOINLINE` on `queue`
* Only use `s` once (not possible in practice)
* Remove the input so that `terrible :: Signal ()` (not possible in practice)

There are two places in the compiler where replicate gets unfolded: 
https://github.com/clash-lang/clash-compiler/blob/dd37ac9b4c858e041f94023f97893c6b7305792b/clash-lib/src/CLaSH/Normalize/Transformations.hs#L1052 and 
https://github.com/clash-lang/clash-compiler/blob/d6f43d9a2fe8822bbd7c3b9df227a589094dd272/clash-ghc/src-ghc/CLaSH/GHC/Evaluator.hs#L245

It's the one in `Transformations.hs` that has the problem.  With it commented out everything works fine.  (With the one in `Evaluator.hs` commented out it still has a problem.)

    {-# LANGUAGE DataKinds, TypeOperators, FlexibleContexts #-}
    {-# LANGUAGE NoImplicitPrelude #-}
    {-# LANGUAGE ScopedTypeVariables #-}
    
    module M
      ( terrible
      ) where
    
    import CLaSH.Prelude as P hiding (Char)
    
    {-# ANN terrible
      (defTop { t_name = "anything"
              , t_inputs = [ "foo" ]
              , t_outputs = [ "baz" ]
              }
      )#-}
    terrible :: Signal () -> Signal ()
    terrible _ = undefined <$> s <*> s
      where s = queue (snat :: SNat 1650) undefined
    
    queue :: forall n a. KnownNat (n+1)
          => SNat (n+2) -> Signal a -> Signal a
    queue _ = blockRam (repeat undefined :: Vec (n+1) a)
                       0
                       0
                       (pure True)

**Comment by tomjaguarpaw** [comment]
Thanks!

**Comment by christiaanb** [comment]
@tomjaguarpaw Please let me know (here or on IRC) if this also fixes the problem in your real code.
