### ISSUE TITLE
'shrink'ing (BitVector 1) gives 'Exception: divide by zero' 

### ISSUE THREAD

**Issue by samgd** [clash-lang/clash-compiler#153]
The [Arbitrary instance for BitVector](https://hackage.haskell.org/package/clash-prelude-0.10.9/docs/src/CLaSH-Sized-Internal-BitVector.html#line-574) is defined using [shrinkIntegral](https://hackage.haskell.org/package/QuickCheck-2.8.2/docs/src/Test-QuickCheck-Arbitrary.html#shrinkIntegral), shown below.

```
-- | Shrink an integral number.
shrinkIntegral :: Integral a => a -> [a]
shrinkIntegral x =
  nub $
  [ -x
  | x < 0, -x > x
  ] ++
  [ x'
  | x' <- takeWhile (<< x) (0:[ x - i | i <- tail (iterate (`quot` 2) x) ])
  ]
 where
   -- a << b is "morally" abs a < abs b, but taking care of overflow.
   a << b = case (a >= 0, b >= 0) of
            (True,  True)  -> a < b
            (False, False) -> a > b
            (True,  False) -> a + b < 0
            (False, True)  -> a + b > 0
```

This definition causes a `*** Exception: divide by zero` as `x 'quot' 2 == x 'quot' 0` because `(2 :: BitVector 1) == 0`.

**Comment by christiaanb** [comment]
Thanks for the report. I really should have given the arbitrary instances more thought. I'm on holiday right now, but will be back on the 5th of July.
