### ISSUE TITLE
How to convert from Fixed to Double?

### ISSUE THREAD

**Issue by tomjaguarpaw** [clash-lang/clash-compiler#158]
There is no obvious way to convert from a `Fixed` to a `Double`.  I used `unSF` or `unUF`, `fromIntegral` and then divided by 2 to the number of decimal places.  Is there a better way?  If not could something be added to the `Fixed` module?

**Comment by christiaanb** [comment]
I guess `Fixed` is missing a `Real` instance so one can use `realToFrac`.
