### ISSUE TITLE
msb (x :: Signed m) broken for m > 64

### ISSUE THREAD

**Issue by jonfowler** [clash-lang/clash-compiler#1599]
```
> msb <$> [0..20 :: Signed 65]
[0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0]
```
:dizzy_face:

**Comment by martijnbastiaan** [comment]
Has been fixed [in 1.2.5](https://github.com/clash-lang/clash-compiler/blob/master/CHANGELOG.md#125-november-9th-2020), thanks for the report!
