### ISSUE TITLE
Errors in the Clash.Prelude.BlockRam.File documentation

### ISSUE THREAD

**Issue by lesjon** [clash-lang/clash-compiler#1608]
The examples given on [hackage 1.2.5](http://hackage.haskell.org/package/clash-prelude-1.2.5/docs/Clash-Prelude-BlockRam-File.html#v:blockRamFile) and 1.3.0 do not compile.
For example the lines
`f :: HiddenClock dom  -> Signal dom (Unsigned 3) -> Signal dom (Unsigned 9)
f rd = unpack <$> exposeClock blockRamFile clk d7 "memory.bin" rd (pure Nothing)`
 should be changed to something like:

`f :: (HiddenClock dom, HiddenEnable dom) => Signal dom (Unsigned 3) -> Signal dom (Unsigned 9)
f rd = unpack <$> blockRamFile d7 "memory.bin" rd (pure Nothing)`

**Comment by christiaanb** [comment]
Thanks for the report. We plan to put all of our examples in doctests so that everything gets checks. It does mean the examples will go from looking like:
```
f x = e
  where
    e = g ...
```
to:
```
>>> :{
f x = e
  where
    e = g ...
```
But having correct-and-checked examples is probably worth that extra line noise
