### ISSUE TITLE
[clash-prelude] doctests:  executable not found

### ISSUE THREAD

**Issue by juhp** [clash-lang/clash-compiler#1622]
For the Stackage Nightly build:

```
Test suite failure for package clash-prelude-1.2.5
    doctests:  executable not found
```

The rest of the tests all seem to pass.

**Comment by ezzieyguywuf** [comment]
I've run into this issue before with other packages - see [this issue](https://github.com/haskell/cabal/issues/7213) with the cabal project for more info.

**Comment by christiaanb** [comment]
So it seems our options are:
1. Stop using `cabal-doctest` and a custom `Setup.hs`, which is rather annoying, since it actually fixed some issues we had with our doctests
2. Wait for the upstream `Cabal`-the-library fix

Both are quite unsatisfactory... we'll have to think about how to solve this.

**Comment by martijnbastiaan** [comment]
As a workaround, perhaps we could patch `Setup.hs` to always run `build` after `haddock`?

**Comment by ezzieyguywuf** [comment]
I can confirm that running build after haddock works as a temporary
workaround, it's what we're doing in gentoo

**Comment by martijnbastiaan** [comment]
My suggestion doesn't really seem feasible: the various commands passed to `Setup.hs` might have wildly different arguments, hence making it brittle at best. Perhaps Stackage could work around this by running tests first and only then run Haddock?

**Comment by christiaanb** [comment]
@martijnbastiaan I think your suggestion isn’t that fragile: just intercept all the arguments and pass them along unchanged to `defaultMainWithDoctests` (or `defaultMain`), but when the arguments contain the string “haddock” we simply call `defaultMainWithDoctests` again, only this time with a single “build” argument.

**Comment by martijnbastiaan** [comment]
Yeah, the reason I'm saying it might be brittle is that I ran it and saw (something like):

```
command --builddir dist_newstyle/foo --another-flag
```

If we don't pass `--builddir` we might regenerate files in the wrong place. If we do pass the flags we risk passing haddock only flags to `build`. But we might as well try :)
