### ISSUE TITLE
`createDomain` creates definitions without documentation

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#1674]
This is an issue when trying to achieve 100% documentation coverage. E.g.:

```
  Missing documentation for:
    Core (src/Config.hs:11)
    vCore (src/Config.hs:11)
```

**Comment by alex-mckenna** [comment]
Not much we can do for this right? Haddock's _floating documentation_ doesn't let you attach docs to a specific entity I don't think, and we can't generate docs with TH currently. Unless you have some idea?

**Comment by martijnbastiaan** [comment]
> and we can't generate docs with TH currently. 

Right, I forgot that. That's pretty annoying.

Haddock should probably get an option to locally disable specific warnings (and it should get a `-Werror` pff). Marking this `external bug` (external feature?) for now.

**Comment by christiaanb** [comment]
GHC 9.2 will solve this, I think: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3330

**Comment by alex-mckenna** [comment]
> external bug (external feature?)

You say potato, I say :potato:
