### ISSUE TITLE
Clash.Tutorial

### ISSUE THREAD

**Issue by jkensik** [clash-lang/clash-compiler#1733]
while I was going through the tutorial I got a type error when it was discussing polymorphism of circuits.

After writing the definition of mac that uses macT and ma, I get this 

src\MAC.hs:11:7: error:
    * Unbound implicit parameters
        (ghc-prim-0.6.1:GHC.Classes.IP
           (Clash.Signal.HiddenClockName dom0) (Clock dom0),
         ghc-prim-0.6.1:GHC.Classes.IP
           (Clash.Signal.HiddenEnableName dom0) (Enable dom0),
         ghc-prim-0.6.1:GHC.Classes.IP
           (Clash.Signal.HiddenResetName dom0) (Reset dom0))
        arising from a use of `mealy'
    * In the expression: mealy macT 0
      In an equation for `mac': mac = mealy macT 0
    * Relevant bindings include
        mac :: Signal dom0 (o0, o0) -> Signal dom0 o0
          (bound at src\MAC.hs:11:1)
   |
11 | mac = mealy macT 0
   |       ^^^^^^^^^^^^

src\MAC.hs:11:7: error:
    * Ambiguous type variable `dom0' arising from a use of `mealy'
      prevents the constraint `(KnownDomain dom0)' from being solved.
      Relevant bindings include
        mac :: Signal dom0 (o0, o0) -> Signal dom0 o0
          (bound at src\MAC.hs:11:1)
      Probable fix: use a type annotation to specify what `dom0' should be.
      These potential instances exist:
        instance KnownDomain IntelSystem
          -- Defined in `Clash.Signal.Internal'
        instance KnownDomain System -- Defined in `Clash.Signal.Internal'
        instance KnownDomain XilinxSystem
          -- Defined in `Clash.Signal.Internal'
    * In the expression: mealy macT 0
      In an equation for `mac': mac = mealy macT 0
   |
11 | mac = mealy macT 0
   |       ^^^^^^^^^^^^

src\MAC.hs:11:13: error:
    * Ambiguous type variable `o0' arising from a use of `macT'
      prevents the constraint `(Num o0)' from being solved.
      Relevant bindings include
        mac :: Signal dom0 (o0, o0) -> Signal dom0 o0
          (bound at src\MAC.hs:11:1)
      Probable fix: use a type annotation to specify what `o0' should be.
      These potential instances exist:
        instance Num a => Num (Signal dom a)
          -- Defined in `Clash.Signal.Internal'
        instance KnownNat n => Num (Signed n)
          -- Defined in `Clash.Sized.Internal.Signed'
        instance Num Integer -- Defined in `GHC.Num'
        ...plus five others
        ...plus 49 instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    * In the first argument of `mealy', namely `macT'
      In the expression: mealy macT 0
      In an equation for `mac': mac = mealy macT 0
   |
11 | mac = mealy macT 0
   |             ^^^^

This is my code 

` module MAC where

import Clash.Prelude

ma acc (x,y) = acc + x * y

macT acc inp = (ma acc inp,acc)

mac = mealy macT 0
`

**Comment by christiaanb** [comment]
Thanks for the report! I've fixed the tutorial in #1735   we'll be sure to include it in the 1.4.1 release.
