### ISSUE TITLE
`BiSignal` is not listed correctly in `clash-manifest.json`

### ISSUE THREAD

**Issue by alex-mckenna** [clash-lang/clash-compiler#1843]
`BiSignalIn` / `BiSignalOut` are used in clash to provide `inout` ports to an entity. In the manifest these should be listed as a single port with an `inout` direction. However, currently the `BiSignalIn` is listed as an in port (without it's domain) and the `BiSignalOut` is not listed at all.

**Comment by martijnbastiaan** [comment]
> without it's domain

Related: https://github.com/clash-lang/clash-compiler/issues/1711

**Comment by alex-mckenna** [comment]
#1844 does not solve the issue of not showing the domain, but this is caused by the same thing as #1711, so this issue can be closed now that `inout` ports are rendered.
