### ISSUE TITLE
Generate a single output file 

### ISSUE THREAD

**Issue by expipiplus1** [clash-lang/clash-compiler#186]
It would be nice to have just a single output file generated by CLaSH.

**Comment by martijnbastiaan** [comment]
Related: https://github.com/clash-lang/clash-compiler/pull/432

**Comment by martijnbastiaan** [comment]
This has been added in PR #432, as part of PR #498. To use the old inline strategy, use `-fclash-old-inline-strategy`. Thanks for the report!
