### ISSUE TITLE
Building with stack fails due to ghci

### ISSUE THREAD

**Issue by beojan** [clash-lang/clash-compiler#196]
Building with stack (as explained in the FAQ) fails because nightly-2017-01-17 uses ghci 8.0.1, but we are building with ghc 8.0.2.

**Comment by christiaanb** [comment]
I you really want to use ghc-8.0.2 and stack right now, you will need to add the `extra-deps` mentioned in to your `stack.yaml`: https://github.com/clash-lang/clash-compiler/blob/0.7/stack-nightly-ghc802.yaml

**Comment by beojan** [comment]
~~I *don't* particularly want to use 8.0.2~~ Never mind, turned out there was a 
`compiler-check: newer-minor` in my `config.yaml`.
