### ISSUE TITLE
reportTimeDiff formats time inconveniently

### ISSUE THREAD

**Issue by danielsmw** [clash-lang/clash-compiler#1989]
So this is a pretty minor issue, but just for the record, here's some output from my compilation:
```
GHC: Parsing and optimising modules took: 13.392s
GHC: Loading external modules from interface files took: 0.004s
GHC: Parsing annotations took: 0.009s
Clash: Parsing and compiling primitives took 0.106s
GHC+Clash: Loading modules cumulatively took 17.499s
Clash: Compiling Quasisystolic.MLP2.topEntity
Clash: Normalization took 23h59m53015.564s
Clash: Netlist generation took 17.250s
Clash: Total compilation took 23h59m53063.423s
```
I don't understand the formatting strings used to specify `Clock.formatTime`, but lumping 15 hours into the seconds field seems a bit ridiculuos.

**Comment by christiaanb** [comment]
Ah, this is the problem: https://github.com/clash-lang/clash-compiler/blob/365cbde57dfeff67f4f971de9a076d5dc8ac1a72/clash-lib/src/Clash/Util.hs#L271-L276

We never considered runs lasting longer than a day... we "need" to add:
```haskell
fmt | diff >= 86400
    = "%-Dd%-Hh%-Mm%-S%03Qs"
```
