### ISSUE TITLE
Allow custom primitive locations

### ISSUE THREAD

**Issue by dented42** [clash-lang/clash-compiler#200]
Currently when using `clash` to compile a design, the compiler only searches for primitives in the current directory and alongside the compiler itself (in `CABAL_DIR`).

It'd be very helpful if one could specify during invocation an additional directory to search for primitives, something along the lines of `clash -clash-prims src/primitives src/Thing/Main.hs`.

**Comment by christiaanb** [comment]
This can now be done using the standard `-i<DIR>` flags through: https://github.com/clash-lang/clash-compiler/commit/48b3472a0e69826bb37d716061276cf0b5cb0d17
