### ISSUE TITLE
CI caching broken

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#2075]
For some reason we end up with empty caches on our CI:

![Selection_016](https://user-images.githubusercontent.com/5658854/152399336-98fe7577-52f0-4b43-a878-283afc925d84.png)

We should investigate:

 - [ ] Whether this originates from a single runner
 - [ ] Whether there's something wrong with our with our cache server (`diepenheim`)

**Comment by alex-mckenna** [comment]
If Diepenheim is low on disk space again, that may explain things

**Comment by martijnbastiaan** [comment]
```
/dev/mapper/diepenheim--vg-root  915G  578G  291G  67% /
```

doesn't look like it..

**Comment by martijnbastiaan** [comment]
The are the last 5 jobs that have an empty cache:

* https://gitlab.com/clash-lang/clash-compiler/-/jobs/2048388879
* https://gitlab.com/clash-lang/clash-compiler/-/jobs/2048388904
* https://gitlab.com/clash-lang/clash-compiler/-/jobs/2050127584
* https://gitlab.com/clash-lang/clash-compiler/-/jobs/2050127731
* https://gitlab.com/clash-lang/clash-compiler/-/jobs/2050127583

I think I see a pattern..

**Comment by alex-mckenna** [comment]
So `gammelke` is polluting the cache? For the time being can we disable it as a runner and confirm that is the problem?

**Comment by martijnbastiaan** [comment]
I'm fairly sure this is due to some experimenting Leon and I did trying to reduce SSD wear and tear. I've put in clean config - if this doesn't fix it I'll completely disable it.

**Comment by martijnbastiaan** [comment]
I've seen the new config create proper caches!
