### ISSUE TITLE
Release 1.6

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#2077]
TODO:

- [x] Finish or move items in [1.6 milestone](https://github.com/clash-lang/clash-compiler/milestone/10)
- [x] Add Mergify backport rules for 1.6
- [ ] Finish [bindist  checklist](https://github.com/clash-lang/clash-compiler/tree/master/.ci/bindist)
  - [ ] https://github.com/clash-lang/clash-compiler/pull/2080
- [x] Write technical release notes: https://github.com/clash-lang/clash-compiler/releases/edit/untagged-369ea5efb222316041a9
- [x] Write "press" release notes (under review)
- [ ] Make sure each link to a PR in the CHANGELOG includes an extended changelog, if the original changelog message contained one.

**Comment by alex-mckenna** [comment]
Can we close this @martijnbastiaan? We have had _two_ 1.6.x releases now :eyes:

**Comment by martijnbastiaan** [comment]
Yes sorry
