### ISSUE TITLE
`fromJustX` should use `deepErrorX`

### ISSUE THREAD

**Issue by jonfowler** [clash-lang/clash-compiler#2112]
Not sure what other peoples opinions are, but personally I think it is best practice to ensure the spine of a structure is always defined (avoiding the need to use lazy patterns everywhere). `fromJustX` doesn't follow this practice as it uses `errorX` as opposed to `deepErrorX`.

**Comment by martijnbastiaan** [comment]
Makes sense to me, lazy patterns are a pain.
