### ISSUE TITLE
clash-prelude-hedgehog's data types should have a Show instance.

### ISSUE THREAD

**Issue by lmbollen** [clash-lang/clash-compiler#2133]
`SomeVec` is a datatype which is used in generators, however Hedgehog's `forAll` function 
https://hackage.haskell.org/package/hedgehog-1.1.1/docs/Hedgehog-Internal-Property.html#v:forAll

`forAll :: (Monad m, Show a, HasCallStack) => Gen a -> PropertyT m a` requires a `Show` instance for `a`.

Hence, all datatypes in `clash-prelude-hedgehog` that are used in generators should have a `Show` instance.

**Comment by martijnbastiaan** [comment]
We've released [v1.6.3](https://github.com/clash-lang/clash-compiler/releases/tag/v1.6.3), which includes a fix for this issue.
