### ISSUE TITLE
`doctest-parallel` fails but doesn't cause CI to fail

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#2179]
https://gitlab.com/clash-lang/clash-compiler/-/jobs/2378113714#L601

**Comment by alex-mckenna** [comment]
It always sets the exit code to 0, it should be setting the exit code to 1 if any of the examples fail.

I blame the author of `doctest-parallel`

**Comment by DigitalBrains1** [comment]
It seems to be specific to `$setup` blocks failing. They do not increase the error count, they do cause the examples after the `$setup` block to be skipped.

**Comment by martijnbastiaan** [comment]
I blame the author of `doctest-parallel`

I hear he is a bit of a character
