### ISSUE TITLE
Add `NFDataX` instances for types in `Data.Functor.*` modules

### ISSUE THREAD

**Issue by alex-mckenna** [clash-lang/clash-compiler#2218]
In `base` there are several types exposed in the `Data.Functor.*` hierarchy which can have instances for `NFDataX` but have been overlooked in Clash:

  * `Identity`
  * `Const`
  * `Product`
  * `Sum`
  * `Compose` (since minimum supported GHC is 8.6 we have `-XQuantifiedConstraints` and can do this too)

We should add instances for these for the users that like to use these types (this issue motivated by a request on the functional programming slack for `NFDataX (Identity a)`)

**Comment by martijnbastiaan** [comment]
We've released [v1.6.4](https://github.com/clash-lang/clash-compiler/releases/tag/v1.6.4), which includes a fix for this issue.
