### ISSUE TITLE
Malformed haddock in `clash-prelude`

### ISSUE THREAD

**Issue by alex-mckenna** [clash-lang/clash-compiler#2278]
The API documentation for [`head` and `tail`](https://hackage.haskell.org/package/clash-prelude-1.6.3/docs/Clash-Sized-Vector.html#v:head) for the current stable version of Clash is slightly malformed, resulting in the documentation being rendered badly. I see:

![Screenshot from 2022-07-10 17-53-58](https://user-images.githubusercontent.com/29676050/178152212-a56a1801-9c36-4169-8b76-930555ac6b14.png)

Looking at the source, the functions causing problems attempt to use the preprocessor to change what is displayed:

```haskell
{- | Extract the first element of a vector

>>> head (1:>2:>3:>Nil)
1

#if __GLASGOW_HASKELL__ >= 900
>>> head Nil
<BLANKLINE>
<interactive>:...
    • Couldn't match type ‘1’ with ‘0’
      Expected: Vec (0 + 1) a
        Actual: Vec 0 a
    • In the first argument of ‘head’, namely ‘Nil’
      In the expression: head Nil
      In an equation for ‘it’: it = head Nil

#else
>>> head Nil
<BLANKLINE>
<interactive>:...
    • Couldn't match type ‘1’ with ‘0’
      Expected type: Vec (0 + 1) a
        Actual type: Vec 0 a
    • In the first argument of ‘head’, namely ‘Nil’
      In the expression: head Nil
      In an equation for ‘it’: it = head Nil

#endif
-}
```

**Comment by leonschoorl** [comment]
That is caused by https://github.com/haskell/haddock/issues/1382
