### ISSUE TITLE
Clash doesn't properly reset terminal boldness after emitting a warning

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#2309]
See:

![Selection_001](https://user-images.githubusercontent.com/5658854/186927501-84790867-3d6e-430a-b26f-605edb21e425.png)

**Comment by rowanG077** [comment]
It does for me. When I look at the raw output it actually does the correct thing:

```
Clash: Normalization took 0.001s
[1m[WARNING] Dubious primitive instantiation for GHC.Num.Integer.integerAdd: GHC.Num.Integer.integerAdd: Integers are dynamically sized in simulation, but fixed-length after synthesis. Use carefully. (disable with -fclash-no-prim-warn)
[0mClash: Netlist generation took 0.000s
Clash: Compiling TopEntity.topEntity took 0.047s
Clash: Total compilation took 0.584s
```

`[1m[` starts bold `[0m` ends bold. If you look at the raw output do you also so these?

**Comment by rowanG077** [comment]
@martijnbastiaan You could try this in your terminal to see if your terminal does the correct thing: `echo "echo "notbold\n\033[1mbold\n\033[0mnotbold"`

**Comment by martijnbastiaan** [comment]
Hmm, good point. So this is probably Shake interfering. Thanks for checking!
