### ISSUE TITLE
`hasX` might hide exceptions other than `XException`

### ISSUE THREAD

**Issue by DigitalBrains1** [clash-lang/clash-compiler#2450]
If the value evaluated with `hasX` contains multiple exceptions, only the first one encountered will determine the outcome of `hasX`.

```haskell
>>> let a = errorX "XException" :> error "ErrorCall" :> Nil
>>> let b = error "ErrorCall" :> errorX "XException" :> Nil
>>> hasX a
Left "X: XException\nCallStack (from HasCallStack):\n  errorX, called at <interactive>:1:9 in interactive:Ghci2"
>>> hasX b
*** Exception: ErrorCall
CallStack (from HasCallStack):
  error, called at <interactive>:2:9 in interactive:Ghci3
```

In my opinion, both should have thrown an `ErrorCall`. The documentation for `hasX` describes it as _fully evaluate a value_. It is currently not evaluating anything beyond the `XException`.

Currently, `hasX` reduces its argument to normal form using `NFData`, and catches `XException`s. This checks only one of the exceptions the argument might throw. Instead, we probably need to first check for exceptions other than `XException` and only after that check for all exceptions (which boils down to just the `XException`s of course):

```haskell
hasX :: (NFDataX a, NFData a) => a -> Either String a
hasX a =
  unsafeDupablePerformIO
    (catch
      (evaluate (rnfX a `seq` rnf a) >> return (Right a))
      (\(XException msg) -> return (Left msg)))
```

**Comment by christiaanb** [comment]
We've released [v1.8.0](https://github.com/clash-lang/clash-compiler/releases/tag/v1.8.0), which includes a fix for this issue.
