### ISSUE TITLE
`deconstructProduct` does not extract fields from given product

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#2469]
The implementation of `deconstructProduct`:

https://github.com/clash-lang/clash-compiler/blob/3e2f3dd3f6c30f60acaec7d1013eba26d492e5f2/clash-lib/src/Clash/Primitives/DSL.hs#L364-L367

..does not do what it promises to at all. It should return a list of expressions representing all the fields of the given product type. It should probably also handle cases where the given expression is _not_ a plain `Identifier`.

**Comment by christiaanb** [comment]
We've released [v1.8.0](https://github.com/clash-lang/clash-compiler/releases/tag/v1.8.0), which includes a fix for this issue.
