### ISSUE TITLE
Getting Started Update

### ISSUE THREAD

**Issue by monibahmed** [clash-lang/clash-compiler#2679]
I'm just going through the documentation, i'll point out issues as I see them.

docs/getting-started/first-circuit.rst:

Need to add to imports:
`import Clash.Explicit.Testbench
`

**Comment by leonschoorl** [comment]
Thanks for the report.

Where are you reading this?
Because it seems to be there:
https://github.com/clash-lang/clash-compiler/blob/master/docs/getting-started/first-circuit.rst?plain=1#L14-L19

**Comment by monibahmed** [comment]
You're right, I see it in the tutorials now.
