### ISSUE TITLE
stringsearch is abandoned

### ISSUE THREAD

**Issue by locallycompact** [clash-lang/clash-compiler#2726]
clash-lib has a dependency on stringsearch which has been abandoned and has no accessible source on bitbucket.

https://hackage.haskell.org/package/stringsearch

Would the preference here be to fork it from tarball and request maintainership, or replace this library with something else? (Not sure what)

**Comment by martijnbastiaan** [comment]
We only use it here:

https://github.com/clash-lang/clash-compiler/blob/e6522d73beb26108aaceb917af7f38e1f978b6ec/clash-lib/tools/v16-upgrade-primitives.hs#L94

There are probably ways to remove that dependency :).

**Comment by christiaanb** [comment]
We've released [v1.8.2](https://github.com/clash-lang/clash-compiler/releases/tag/v1.8.2), which includes a fix for this issue.
