### ISSUE TITLE
Shifting bits to 0-length `BitVector`s fails

### ISSUE THREAD

**Issue by kleinreact** [clash-lang/clash-compiler#2730]
Shifting a bit into a 0-length BitVector with `(+>>.)` or `(.<<+)` currently fails with an out of range exception.

We should either define the operations to keep empty bit vectors unchanged or exclude them from the interface via adding some `1 <= n` constraints.

The former would be the way to go in order to stay consistent with `(+>>)` and `(<<+)`:
```haskell
clashi> high +>> (Nil :: Vec 0 Bit)
Nil
clashi> (Nil :: Vec 0 Bit) <<+ low
Nil
```

**Comment by christiaanb** [comment]
We've released [v1.8.2](https://github.com/clash-lang/clash-compiler/releases/tag/v1.8.2), which includes a fix for this issue.
