### ISSUE TITLE
Surprising type defaulting

### ISSUE THREAD

**Issue by leonschoorl** [clash-lang/clash-compiler#280]
Taking the 3 least significant bits of 5 in clashi:
```
Clash.Prelude> slice d2 d0 5
000
```

Why not `101`?

Because of [type defaulting](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html#type-defaulting-in-ghci), clashi picks the type of 5 to be Double:
```
Clash.Prelude> slice d2 d0 (5::_)
<interactive>:11:17: error:
    • Found type wildcard ‘_’ standing for ‘Double’
```

Note that this only happens in clashi.
Doing the same in a .hs file, results in an ambiguous type variable error.

But I think clashi should never default to Double.

**Comment by masterdezign** [comment]
Hi!

I think, there is no reason for `101` unless bu default `5 :: Unsigned 32` or something like that. 
If by default `5 :: Double`, than it means that `slice d2 d0` takes the tail of the fractional part, which is zero. That is why you get `000`.

**Comment by christiaanb** [comment]
We should get an ambiguity error
