### ISSUE TITLE
<<loop>> in simulation

### ISSUE THREAD

**Issue by adamwalker** [clash-lang/clash-compiler#350]
The code below prints `<<loop>>` when compiled to an executable with clash-ghc 0.9.3.
This is unexpected because there is no combinational loop in the design. Instead, I would expect a sequence of Xs.

```
import Clash.Prelude

bug = blockRamPow2 (repeat (0 :: Unsigned 1)) bug (pure Nothing)

main = mapM printX $ sampleN 40 bug
    
```

**Comment by martijnbastiaan** [comment]
@christiaanb could you check if the patch ( ^^ ) meets your expectations?

**Comment by christiaanb** [comment]
@martijnbastiaan LGTM
