### ISSUE TITLE
Automatic testing of examples...

### ISSUE THREAD

**Issue by mgajda** [clash-lang/clash-compiler#38]
Hi,

I've just tried to compile clash example `Fifo.hs` with the 0.6 compiler, and got an error:

[1 of 1] Compiling Fifo             ( Fifo.hs, Fifo.o )

Fifo.hs:14:23: Not in scope: type constructor or class ‘SingRep’

Fifo.hs:14:34: Not in scope: type constructor or class ‘SingI’

Fifo.hs:14:47: Not in scope: type constructor or class ‘SingI’

Fifo.hs:25:13:
    Not in scope: ‘resizeU’
    Perhaps you meant one of these:
      ‘resize’ (imported from CLaSH.Prelude),
      ‘resizeF’ (imported from CLaSH.Prelude)

Fifo.hs:29:25:
    Not in scope: ‘vreplace’
    Perhaps you meant ‘replace’ (imported from CLaSH.Prelude)

Fifo.hs:32:23: Not in scope: ‘fromSing’

Fifo.hs:32:33:
    Not in scope: ‘sing’
    Perhaps you meant one of these:
      ‘sin’ (imported from CLaSH.Prelude),
      ‘sinh’ (imported from CLaSH.Prelude)

Fifo.hs:32:41: Not in scope: type constructor or class ‘Sing’

Fifo.hs:38:15: Not in scope: ‘vindex’

Fifo.hs:40:10: Not in scope: type constructor or class ‘Comp’

Fifo.hs:41:14:
    Not in scope: ‘^^^’
    Perhaps you meant ‘^^’ (imported from CLaSH.Prelude)

Fifo.hs:41:23: Not in scope: ‘vcopyE’

Fifo.hs:41:31:
    Not in scope: ‘sing’
    Perhaps you meant one of these:
      ‘sin’ (imported from CLaSH.Prelude),
      ‘sinh’ (imported from CLaSH.Prelude)

Fifo.hs:41:39: Not in scope: type constructor or class ‘Sing’
Would be great to know how to fix it, or get a CI to compile examples  (I use Travis CI, may give config.)

**Comment by christiaanb** [comment]
All examples are now automatically tested as of: https://github.com/clash-lang/clash-compiler/commit/99e7d691eca6729a793ebdaf1c0e4245787dbe55
