### ISSUE TITLE
Tutorial for custom clocks?

### ISSUE THREAD

**Issue by mgajda** [clash-lang/clash-compiler#39]
I'd like to generate a circuit with several custom clocks, but didn't find any tutorial as of how to do it.
Example applications may be:
* to use 1kHz clock for seven segment display controller, while rest of FPGA runs 32MHz,
* to use 9.6kHz clock for UART controller,
* to use output from clock divider circuit to drive real time clock at 1Hz.

Note that using clock at lower frequency could save power.

**Comment by masterdezign** [comment]
Hi!

Do you have any updates? 

Thanks

**Comment by christiaanb** [comment]
Yes, thanks for the reminder. I've started on a section on multi-clock designs by describing how to make an asynchronous, multi-clock, FIFO described in: http://www.sunburst-design.com/papers/CummingsSNUG2002SJ_FIFO1.pdf

This commit adds the code example to the tutorial: https://github.com/clash-lang/clash-prelude/commit/95c14e57a5273dd4726ea5b582c9744c44f594fc

I hope to make a new release of CLaSH over the weekend which includes the tutorial updated with info on how to do multi-clock designs.

**Comment by masterdezign** [comment]
Thank you for the useful information in 95c14e5.

B

**Comment by mgajda** [comment]
Indeed, now I can try tunable UART on my fresh Cyclone IV.



-- 
  Pozdrawiam
    Michał

**Comment by christiaanb** [comment]
Is http://hackage.haskell.org/package/clash-prelude/docs/CLaSH-Tutorial.html#g:13 enough to close this ticket?

**Comment by masterdezign** [comment]
Yes, it seems to be enough.

**Comment by mgajda** [comment]
Working through it and planning my book "Haskell from logic gates to
photoreal goblins."

>

-- 
  Pozdrawiam
    Michał
