### ISSUE TITLE
Automatically generate qsys/coregen files when using IP

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#545]
Using IP in Clash is quite cumbersome right now. Take `alterapll`. When used, a user is expected to:

1. Start QSys
2. Make sure the names/values correspond to their Clash desgin
3. Generate the HDL files
4. Include it in their design

We should investigate if it's possible to automatically generate and include the files generated by qsys (or invoke qsys somehow).

**Comment by rowanG077** [comment]
Qsys designs can be automatically created using TCL scripts. The best option might be to generate the TCL scripts manually, qsys can then be invoked to generate the system.
