### ISSUE TITLE
clash-prelude needs a bounds bump to work with 8.6.3

### ISSUE THREAD

**Issue by gbaz** [clash-lang/clash-compiler#549]
can be done as a revision on hackage, and also just an in-repo bump without a new release

**Comment by leonschoorl** [comment]
We could probably do this for clash-prelude, but it won't work for clash-ghc.
But I don't know how useful it would be to have only clash-prelude-0.99.3 available on GHC-8.6.

**Comment by christiaanb** [comment]
Fixed with the 1.0 release
