### ISSUE TITLE
no alternative for satMin and its relatives for Unsigneds

### ISSUE THREAD

**Issue by rowanG077** [clash-lang/clash-compiler#644]
In the current master branch `satMin` and its relatives are no longer available compared to the version released on Hackage. I use these functions to subtract an `Unsigned` from another `Unsigned`. I don't see how to achieve the same thing in the current codebase since it's not possible to have negative unsigneds nor can I use `satAdd` to add a `Signed` to an `Unsigned`.

**Comment by martijnbastiaan** [comment]
They've been renamed:

```
satPlus -> satAdd
satMin -> satSub
satMult -> satMul
```

I believe these should be available on `Unsigned`s?

**Comment by rowanG077** [comment]
Yes true. I didn't see the renames. Sorry!
