### ISSUE TITLE
SResetPolarity not exported by Prelude

### ISSUE THREAD

**Issue by gergoerdi** [clash-lang/clash-compiler#647]
I have to manually

```
import Clash.Signal.Internal (SResetPolarity(..))
```

to be able to define my own `KnownDomain`s. That is probably not intended.

**Comment by martijnbastiaan** [comment]
Hmm, I'm not sure. I'd like people to use `createDomain`, as its much more ergonomic than creating your own instances. See:

https://github.com/clash-lang/clash-compiler/blob/master/clash-prelude/src/Clash/Signal/Internal.hs#L394

The docs at

https://github.com/clash-lang/clash-compiler/blob/master/clash-prelude/src/Clash/Signal.hs#L46-L49

could probably mention this.

**Comment by martijnbastiaan** [comment]
Actually, it should be exported as it has a valid usecase in combination with `knownDomain` - just like the other GADTs are. I'll merge a patch soon.
