### ISSUE TITLE
Port naming doesn't match documentation

### ISSUE THREAD

**Issue by leonschoorl** [clash-lang/clash-compiler#654]
While updating the examples in `Clash.Annotations.TopEntity` because of #646
I found this example:

```haskell
{-# ANN f
   (Synthesize
      { t_name   = "f"
      , t_inputs = [ PortName "a"
                   , PortProduct "" [ PortName "b", PortName "c" ] ]
      , t_output = PortProduct "res" [PortName "q"] }) #-}
f :: Int -> T -> (T,Bool)
f a b = ...
```
Which according to the documentation would generates:
```
entity f is
  port(a     : in signed(63 downto 0);
       b     : in signed(63 downto 0);
       c     : in boolean;
       q     : out f_types.t;
       res_1 : out boolean);
end;
```

But current master generates:
```
entity f is
  port(a     : in signed(63 downto 0);
       b     : in signed(63 downto 0);
       c     : in boolean;
       res_q : out f_types.t;
       res_1 : out boolean);
end;
```
(It always uses the prefix string from the PortProduct.)
From the the text it isn't clear what should happen, there is only this example.

If you want the first output port to be named exactly `q` you can change the `"res"` to `""`, but then the second output port might get a surprising name(depending on the body of `f`):
```
entity f is
  port(a              : in signed(63 downto 0);
       b              : in signed(63 downto 0);
       c              : in boolean;
       q              : out f_types.t;
       \c$case_alt_1\ : out boolean);
end;
```

What do we want to happen here?

**Comment by christiaanb** [comment]
Change the documentation. The current prefixing behavior is what we want.
