### ISSUE TITLE
Fifo example has a typo

### ISSUE THREAD

**Issue by polygonhell** [clash-lang/clash-compiler#66]
Surely all of these n^2 should be 2^n

fifo :: forall n e . (KnownNat n, KnownNat (n+1), KnownNat (n^2))
     => (Pntr n, Pntr n, Vec (n^2) e)
     -> (e, Bool, Bool)
     -> ((Pntr n,Pntr n,Vec (n^2) e),(Bool,Bool,e))
fifo (rpntr, wpntr, elms) (datain,wrt,rd) = ((rpntr',wpntr',elms'),(full,empty,dataout))

**Comment by christiaanb** [comment]
Thanks for  the report, you are indeed correct. It is fixed now.
