### ISSUE TITLE
Merge "Clash.Prelude.{BitIndex,BitReduction}" into "Clash.Sized.BitVector"

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#664]
Functions such as `msb`, `lsb`, `reduceAnd`, etc. are hard to discover as recently discussed on the mailing list. Most users (including yours truly, who was blissfully unaware of the modules these functions reside in) will look in `Clash.Sized.BitVector`. Worse, some users have tried to use the primitives `msb#`, etc. in `Clash.Sized.Internal.BitVector` because they couldn't find the others!

We should therefore get rid of `Clash.Prelude.{BitIndex,BitReduction}` and merge them into  `Clash.Sized.BitVector`.

**Comment by christiaanb** [comment]
@martijnbastiaan But those operations work on more types than `BitVector`, how about moving them to `Clash.Class.BitPack`?

**Comment by martijnbastiaan** [comment]
I should have rephrased this issue after having had a discussion about it with @leonschoorl. What it comes down to is the fact that `msb#` and friends are hard to discover. So it may not be necessary to move these modules, as long as they are re-exported at relevant places. Leon has put in some thought on how to best do that.

Still:

> how about moving them to `Clash.Class.BitPack`?

makes sense to me.

**Comment by alex-mckenna** [comment]
Closing: this was done in https://github.com/clash-lang/clash-compiler/commit/2b19b17bf929cd20556ff01c9f1c9791bc3213a8
