### ISSUE TITLE
Pass CPP __CLASH_VERSION__ to code Clash compiles

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#703]
Similar to `__GLASGOW_HASKELL__`. (`__ENSCHEDE_CLASH__` anyone? :-))

**Comment by christiaanb** [comment]
Why? You can use `MIN_VERSION_clash_prelude(0,999,0)`

**Comment by martijnbastiaan** [comment]
Oh alright, I didn't know that this was possible. Thanks!
