### ISSUE TITLE
blockRAM0

### ISSUE THREAD

**Issue by gergoerdi** [clash-lang/clash-compiler#727]
This is a separate ticket for https://github.com/clash-lang/clash-compiler/issues/638#issuecomment-518155363:

> Would it be possible as a temporary workaround to have a blockRam0 which does no initialization at all?

@christiaanb recommended adding it as a separate ticket to increase the chances of considering it for 1.0

**Comment by martijnbastiaan** [comment]
I'd be happy to include it.
