### ISSUE TITLE
rem and quot on Signed are broken

### ISSUE THREAD

**Issue by leonschoorl** [clash-lang/clash-compiler#73]
The types for CLaSH.Sized.Internal.Signed.quot# and rem# don't match between clash-prelude and the primitives.

This causes the compiler the die with:
>    CLaSH Error:
>CLaSH.Netlist.BlackBox(83): 
>Can't match template for "CLaSH.Sized.Internal.Signed.quot#" :
>"~ARG[1] / ~ARG[2]"

You could either change the primitives to match the prelude:
leonschoorl/clash-compiler@e8faa87dc3c13ef491ab4857bb73cbd87765561a

Or the other way round:
leonschoorl/clash-prelude@a67482354017ad7d41e2f829dd0786dcbf1ed079

I'm not sure what the would be the "right way".
Just don't apply both.

**Comment by christiaanb** [comment]
I prefer the change to the primitives. Could you send a pull request?
