### ISSUE TITLE
Generalize `Undefined` to work with non-errors too

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#748]
`deepErrorX` builds the structure/spine of a datatype and puts an error at its "core". This can be generalized such that it "lazyfies" a given type instead. Consider:

```haskell
Clash.Prelude> x = errorX "foo" :: Vec 3 Int
Clash.Prelude> map (const 3) x
<*** Exception: X: foo
```

We could build `lazify` (for the lack of a better name) to achieve:

```haskell
Clash.Prelude> x = lazify (errorX "foo") :: Vec 3 Int
Clash.Prelude> map (const 3) x
<3,3,3>
```

`deepErrorX` can now be defined as:

```haskell
deepErrorX = lazify . errorX
```

**Comment by christiaanb** [comment]
It's somewhat specific to products of a single type though... how do you generalize this to e.g. tuples?

**Comment by martijnbastiaan** [comment]
I'm not sure I understand what you're saying. The implementation for a tuple would be something like:

```haskell
instance (Undefined a, Undefined b) => Undefined (a, b) where
  -- lazify ~(a, b) = (lazify a, lazify b) ?
  lazify ab = 
    ( let (a, _) = ab in lazify a
    , let (_, b) = ab in lazify b
    )
```

**Comment by christiaanb** [comment]
So what's the `class` supposed to look like?

**Comment by martijnbastiaan** [comment]
```haskell
class Undefined a where
  lazify :: a -> a
```

? Could you just explain what issues you're seeing?

**Comment by christiaanb** [comment]
I don't see what the benefit is of having:

```
lazify (1,2,errorX "foo") :: (Int,Int,(Int, Int))
```

over

```
(1,2,deepErrorX "Foo" :: (Int,Int))
```

**Comment by martijnbastiaan** [comment]
Ah right. It allows your to implement `deepLazyV`, if you will.

**Comment by martijnbastiaan** [comment]
To be more specific, `deepLazyV` would be a type specialized version of `lazify`.

**Comment by martijnbastiaan** [comment]
Does that make sense @christiaanb?

**Comment by christiaanb** [comment]
Yeah, that makes sense

**Comment by jonfowler** [comment]
@christiaanb a potential use case is when you have `mux`:
```
mux (errorX "undefined") (pure (repeat 0)) someVecSig
```
will produce `errorX "undefined"`. With `lazify` you could write:
```
lazify $ mux ...
```
which will give you back the structure.
