### ISSUE TITLE
 Could not deduce (NFDataX RxReg) arising from a use of `register'

### ISSUE THREAD

**Issue by postoroniy** [clash-lang/clash-compiler#782]
Tried last 1.0.0 version and dev version 1.1.0 on UART from example page
https://hackage.haskell.org/package/clash-prelude-1.0.0/docs/Clash-Examples.html#g:4
and it shows error
 **Could not deduce (NFDataX RxReg)
 Could not deduce (NFDataX TxReg)**

Also, I could not figure out how to fix this "can not deduce NFDataX"  to make init(reset) value of register for similar type of data(as example)
```Haskel
data Pipe_struct   = Pipe_struct {
                val_r1     :: UWord32,--value of register src1
                val_r2     :: UWord32,--value of register src2
                val_dst    :: UWord32,--value of destination register
...
}
```
update.. found this commit https://github.com/clash-lang/clash-compiler/commit/d1f325e94735bb718867b50b42500a3894f40956
and figured out that repo's examples  had been changed but not example on site
and need to specify ->  **deriving (Generic, NFDataX,Eq,Show)**

**Comment by martijnbastiaan** [comment]
Thanks, will update!
