### ISSUE TITLE
Add pointers to GHC extensions users need to know in order to use basic Clash

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#819]
Paddy mentions on the mailing list that he know has to know specific GHC extensions in order to use Clash. This is fine, but we never mention it in our docs. We should probably do this.

**Comment by alex-mckenna** [comment]
Is this covered by [this page in our documentation](https://clash-lang.readthedocs.io/en/latest/developing-hardware/language.html)?

**Comment by martijnbastiaan** [comment]
Yes :).
