### ISSUE TITLE
`CustomProduct` is missing from `HWType`

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#880]
..and consequently, [`fixCustomReprs`](https://github.com/clash-lang/clash-compiler/blob/master/clash-lib/src/Clash/Netlist/Util.hs#L240) doesn't handle this case. Useful if you want to use some record as a simulation construct only, and therefore would like Clash to ignore any non-representable stuff in there.

**Comment by christiaanb** [comment]
That `fixCustomReprs` definitely needs a top-level comment explaining what it actually does. Especially because `fix` has a well-known meaning in FP circles (i.e. fixpoint), which is probably not the behaviour of that function.

**Comment by martijnbastiaan** [comment]
Yeah..
