### ISSUE TITLE
Improve Test Suite in clash-cores

### ISSUE THREAD

**Issue by alex-mckenna** [clash-lang/clash-compiler#903]
The test suite in `clash-cores` currently runs a lot of similar tests in a manner which is

  * very repetitive, making it harder to read / write cases
  * potentially very specific, and could be more general using QuickCheck for instance

These tests should be refactored to address these problems now that clash-cores lives in the main repository.

**Comment by martijnbastiaan** [comment]
I think @christiaanb was talking about this monster:

https://github.com/clash-lang/clash-compiler/blob/master/testsuite/Main.hs

**Comment by christiaanb** [comment]
@martijnbastiaan No I was talking about the clash-cores one.

**Comment by martijnbastiaan** [comment]
@christiaanb Too bad :P. I'll add another issue for the main testsuite.
