### ISSUE TITLE
Send Acknowledge Signals in SPI

### ISSUE THREAD

**Issue by alex-mckenna** [clash-lang/clash-compiler#908]
Currently when SPI transmits data, it does not send an acknowledge signal to say that the underlying source of the data being sent is free to be changed again. This signal should be added, and the test suite extended to show that data can be changed only after the acknowledge signal has been sent.

**Comment by alex-mckenna** [comment]
850e2b93 has added an acknowledgement signal which appears to intermittently set as expected, however it still needs to be tested for correctness. At a guess, I would assume tests should be able to show things like

  * every data transfer has exactly one acknowledgement at the start
  * data input does not change until after acknowledgement
  * multi-word messages send one acknowledgement for every word in the message

CC: @christiaanb

**Comment by christiaanb** [comment]
@alex-mckenna yes, that test plan sound good

**Comment by alex-mckenna** [comment]
The acknowledge signal is in, and the tests specific to that one signal are implemented to what should hopefully be an acceptable standard. To achieve full feature parity with the lattice SPI reference I've been looking at, an error signal will be added (to be set high for one cycle if the data is changed before an acknowledge signal). The prerequisites in the test suite to write tests for this already exist.
