### ISSUE TITLE
Bug in Type Checker

### ISSUE THREAD

**Issue by paddytheplaster** [clash-lang/clash-compiler#929]
I'd like to report a bug in the typechecker: Clash, version 1.0.1 (using clash-lib, version: 1.0.1).
I am attaching the code. (I tried including the code in a previous attempt to report the bug but for some reason a sequence of 'x' followed by '*' followed by 'x' was turned into 'xx'.

Regards,

Paddy
[BUG.txt](https://github.com/clash-lang/clash-compiler/files/3869478/BUG.txt)

**Comment by christiaanb** [comment]
Right... it seems to do with the order in which the plugins are called.

**Comment by christiaanb** [comment]
And that's because the natnormalise-plugin makes a bad call, and calling the extra-plugin earlier ensures that the natnormalise-plugin cannot mess up.

**Comment by christiaanb** [comment]
@paddytheplaster as a worked-around until the fixed versions are distributed you can add

```
{-# OPTIONS_GHC -fplugin GHC.TypeLits.Extra.Solver #-}
```

to the affected files. At least, that worked for your example, but I can't give any guarantees it's going to be a work-around in any of your normal code.
