### ISSUE TITLE
No mechanism for standalone binary install

### ISSUE THREAD

**Issue by Araneidae** [clash-lang/clash-compiler#965]
I would like to investigate running Clash ... but (let's say) I don't have root on my target workstation.  In the past with other systems I have been able to run a binary distribution in a local prefix (or build into a local prefix), but somehow Clash *insists* that I install a foreign package manager.  This is a problem.

Let's say I have neither Nix nor Snap installed, that neither of these packages is going to be installed, I have no root access, and admin support is not going to be forthcoming.  What are my options?  By the way, ghc runs just fine.

**Comment by martijnbastiaan** [comment]
You can now try Clash by using a [Clash starter project](https://github.com/clash-lang/clash-starters). This only needs Stack or Cabal+GHC, both of which can be installed without root permissions.
